name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  equatable: 
  uuid: ^3.0.5
  meta: ^1.7.0
  http: ^0.13.4
  sqflite: ^2.0.2
  shared_preferences: ^2.0.12
  flutter_dotenv: ^5.0.2
  path_provider: ^2.0.8
  cupertino_icons: ^1.0.4

